export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  skills: [
    "skill",
    "skills",
    "technology",
    "technologies",
    "tech stack",
    "technical skill",
    "technical skills",
    "what does he know",
    "what technologies",
    "programming language",
    "programming languages",
    "languages",
    "tools",
    "framework",
    "frameworks",
    "database",
    "databases",
  ],

  experience: [
    "experience",
    "work experience",
    "work history",
    "worked",
    "work",
    "working",
    "career history",
    "professional experience",
    "internship",
    "internships",
    "intern",
    "company",
    "companies",
    "job",
    "jobs",
    "role",
    "roles",
    "employment",
    "employer",
    "where has he worked",
    "where has sohail worked",
    "where did he work",
    "where does he work",
    "who has he worked for",
    "who did he work for",
    "which companies",
    "previous companies",
    "previous roles",
    "past jobs",
    "past work",
  ],

  education: [
    "education",
    "educational background",
    "educational qualification",
    "academic background",
    "academic qualification",
    "degree",
    "college",
    "university",
    "bca",
    "cgpa",
    "academic",
    "academics",
    "qualification",
    "qualifications",
    "study",
    "studied",
    "school",
  ],

  certifications: [
    "certification",
    "certifications",
    "certificate",
    "certificates",
    "achievement",
    "achievements",
    "award",
    "awards",
  ],

  contact: [
    "contact",
    "email",
    "phone",
    "linkedin",
    "github",
    "social",
    "reach",
    "contact information",
    "how to contact",
    "contact details",
  ],

  career: [
    "career",
    "career goal",
    "career goals",
    "looking for",
    "opportunity",
    "opportunities",
    "open to",
    "future",
  ],

  projects: [
    "project",
    "projects",
    "built",
    "build",
    "application",
    "applications",
    "portfolio project",
  ],

aiMl: [
  "ai",
  "artificial intelligence",
  "machine learning",
  "machine learning technologies",
  "ai technologies",
  "ai technology",
  "ai tools",
  "ai models",
  "ai model",
  "ai experience",
  "worked with ai",
  "worked with artificial intelligence",
  "llm",
  "llms",
  "large language model",
  "large language models",
  "rag",
  "retrieval augmented generation",
  "embedding",
  "embeddings",
  "vector search",
  "lime",
  "tf-idf",
  "logistic regression",
],

  security: [
    "security",
    "cybersecurity",
    "cyber security",
    "waf",
    "firewall",
    "jwt",
    "authentication",
    "authorization",
    "sql injection",
    "xss",
  ],

  engineering: [
    "architecture",
    "system design",
    "backend",
    "api",
    "apis",
    "scalable",
    "scalability",
    "database design",
    "repository pattern",
    "design pattern",
  ],

  resume: ["resume", "cv", "curriculum vitae"],
};
