export const projects = [
  {
    slug: "nexora",
    number: "01",
    name: "Nexora",
    title: "AI Workspace Platform",
    description:
      "A modular AI-powered SaaS workspace with multi-LLM chat, streaming responses, RAG, file intelligence, image generation, web search, analytics, subscriptions, and cloud storage.",
    details:
      "Nexora is designed as a provider-agnostic AI workspace rather than a simple chatbot. It uses an AI routing layer to connect multiple LLM providers while keeping the application flow independent of individual provider SDKs. The platform includes streaming chat, document processing, RAG architecture, multimodal image processing, web search, authentication, analytics, subscriptions, and cloud storage.",
    stack: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "PostgreSQL",
      "Prisma",
      "Vercel AI SDK",
      "Google Gemini",
      "Groq",
      "Cohere",
      "DeepSeek",
      "ChromaDB",
      "Cloudinary",
      "Razorpay",
    ],
    features: [
      "Multi-model AI chat",
      "Streaming AI responses",
      "Gemini, Groq, Cohere, and DeepSeek models",
      "RAG document processing",
      "Google Embeddings",
      "ChromaDB vector architecture",
      "PDF, DOCX, TXT, Markdown, and image processing",
      "AI image generation",
      "HuggingFace image-generation fallback",
      "AI web search with Tavily",
      "Google OAuth",
      "GitHub OAuth",
      "Credentials authentication",
      "JWT sessions",
      "Protected routes",
      "Analytics dashboard",
      "Razorpay subscriptions",
      "Cloudinary storage",
    ],
    liveUrl: "https://nexora-ai-dusky.vercel.app",
    githubUrl: "https://github.com/Developer-Sohail786/Nexora",
  },
  {
    slug: "waf",
    number: "02",
    name: "WAF + JWT",
    title: "Explainable AI-Based Web-Application Firewall + JWT Authentication",
    description:
      "A full-stack security application combining traditional WAF controls with machine-learning-based attack detection, JWT authentication, and LIME-powered explainability.",
    details:
      "The WAF inspects incoming requests through security middleware, applies traditional controls such as IP blocking and rate limiting, and analyzes suspicious payloads using a Python machine-learning component. TF-IDF converts payload text into numerical features and a Logistic Regression model classifies requests as normal, SQL injection, XSS, path traversal, or command injection. LIME provides human-readable explanations for individual predictions.",
    stack: [
      "React",
      "Node.js",
      "Express.js",
      "MongoDB",
      "JWT",
      "Python",
      "Scikit-learn",
      "TF-IDF",
      "Logistic Regression",
      "LIME",
      "Explainable AI",
    ],
    features: [
      "SQL injection detection",
      "XSS detection",
      "NoSQL injection protection",
      "Path traversal detection",
      "Command injection detection",
      "Brute-force protection",
      "IP blocking",
      "Rate limiting",
      "Request filtering",
      "ML-based payload classification",
      "TF-IDF feature extraction",
      "Logistic Regression classification",
      "LIME explanations",
      "JWT authentication",
      "Protected routes",
      "Security logging",
      "Security monitoring dashboard",
    ],
    liveUrl: "https://waf-jwt-frontend.vercel.app",
    githubUrl: "https://github.com/Developer-Sohail786/WAF-JWT",
  },
  {
    slug: "url-shortener",
    number: "03",
    name: "AI URL Shortener",
    title: "AI-Powered Secure URL Shortener",
    description:
      "A full-stack URL management platform that uses Gemini AI to generate meaningful short URL slugs and concise webpage summaries while providing authentication, ownership controls, and click analytics.",
    details:
      "The application combines traditional URL-shortening functionality with AI-powered metadata generation. Authenticated users can create, manage, and track shortened URLs. Gemini analyzes the destination webpage and generates a clean short slug and concise summary, with model and deterministic fallbacks when AI generation fails.",
    stack: [
      "Next.js",
      "React",
      "JavaScript",
      "Tailwind CSS",
      "MongoDB",
      "NextAuth",
      "JWT",
      "Gemini AI",
      "React Hook Form",
      "bcryptjs",
    ],
    features: [
      "AI-generated URL slugs",
      "AI-generated webpage summaries",
      "Gemini model fallback",
      "Deterministic AI fallback",
      "Credentials authentication",
      "Google OAuth",
      "JWT sessions",
      "Protected routes",
      "User-specific URL ownership",
      "Short URL generation",
      "Duplicate URL prevention",
      "URL analytics",
      "Atomic click tracking",
      "Server-side redirects",
      "URL deletion",
    ],
    liveUrl: "https://url-shortener-app-topaz.vercel.app",
    githubUrl: "https://github.com/Developer-Sohail786/url-shortener-app",
  },
] as const;